---
title: "DASC 1104 Project Proposal"
author: "Braden Fowler"
date: '2020-12-03'
output: pdf_document
urlcolor: Blue
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<p>My blog is available at <a href="https://dasc1104-blog-project.netlify.app/" class="uri">https://dasc1104-blog-project.netlify.app/</a></p>
<pre class="r"><code>library(here)
library(ggplot2)
library(tidyverse)
library(readxl)
knitr::opts_chunk$set(echo = FALSE, tidy = TRUE)</code></pre>
<pre><code>## Observations: 188
## Variables: 6
## $ season      &lt;int&gt; 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
## $ episode     &lt;int&gt; 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, …
## $ title       &lt;fct&gt; Pilot, Diversity Day, Health Care, The Alliance, Basketba…
## $ imdb_rating &lt;dbl&gt; 7.6, 8.3, 7.9, 8.1, 8.4, 7.8, 8.7, 8.2, 8.4, 8.4, 8.2, 8.…
## $ total_votes &lt;int&gt; 3706, 3566, 2983, 2886, 3179, 2852, 3213, 2736, 2742, 271…
## $ air_date    &lt;fct&gt; 2005-03-24, 2005-03-29, 2005-04-05, 2005-04-12, 2005-04-1…</code></pre>
<p>For this project, I am going to be looking at Office Ratings data set contained in the office_ratings.csv file on Tidy Tuesday’s website. This data set contains ratings of each episode from the famous US adapted sitcom television series. The data has 188 observation and 6 variables. The variable season tells us which season of the show is being selected from. The variable episode tells us which episode of the season is being selected. The variable title tells us the title of the episode being selected. The variable imdb_rating tell us the rating given for the episode by imdb. The variable total_votes tells us how many people contributed to the imdb_rating; and finally, the variable air_data tells us when that specific episode was aired.</p>
<p>Question 1: What is the highest rated episode?
Question 2: Have the ratings of the episodes changed over time?
Question 3: Which season contains the highest average rating?</p>
<pre><code>## Observations: 2,492
## Variables: 9
## $ date                                  &lt;fct&gt; 1971-04-02, 1971-04-09, 1971-04…
## $ fixed_rate_30_yr                      &lt;dbl&gt; 7.33, 7.31, 7.31, 7.31, 7.29, 7…
## $ fees_and_pts_30_yr                    &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA,…
## $ fixed_rate_15_yr                      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA,…
## $ fees_and_pts_15_yr                    &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA,…
## $ adjustable_rate_5_1_hybrid            &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA,…
## $ fees_and_pts_5_1_hybrid               &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA,…
## $ adjustable_margin_5_1_hybrid          &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA,…
## $ spread_30_yr_fixed_and_5_1_adjustable &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA,…</code></pre>
<pre><code>## Observations: 14
## Variables: 7
## $ name                                 &lt;fct&gt; Great Depression, Recession of 1…
## $ period_range                         &lt;fct&gt; Aug 1929-Mar 1933ct 1929-Dec 194…
## $ duration_months                      &lt;fct&gt; 433 years7 months, 131 year1 mon…
## $ time_since_previous_recession_months &lt;fct&gt; 0211 year9 months, 0504 years2 m…
## $ peak_unemploy_ment                   &lt;fct&gt; 24.921.3%(1932)[45]–  24.9%(1933…
## $ gdp_decline_peak_to_trough           &lt;fct&gt; 26.7−26.7%, 03.4−18.2%, 12.7−12.…
## $ characteristics                      &lt;fct&gt; &quot;A banking panic and a collapse …</code></pre>
<pre><code>## Observations: 26,877
## Variables: 5
## $ year        &lt;int&gt; 1975, 1975, 1975, 1975, 1975, 1975, 1975, 1975, 1975, 197…
## $ month       &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, …
## $ state       &lt;fct&gt; AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, A…
## $ price_index &lt;dbl&gt; 34.63120, 35.10387, 35.49146, 35.87223, 36.28356, 36.7018…
## $ us_avg      &lt;dbl&gt; 23.46149, 23.61079, 23.82459, 24.08920, 24.23425, 24.2171…</code></pre>
<p>Using the data from TidyTuesday’s website, I am going to look at mortgage rates, times in which there was a recession in the United States, and the housing price index over time. The first data set contains 2,492 observations and 9 variables. The second data set contains 14 observations and 7 variables. The third data set contains 26,877 observations and 5 variables.</p>
<p>Question 1:
Question 2:
Question 3:</p>
