% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={DASC 1104 Project Proposal},
  pdfauthor={Braden Fowler},
  colorlinks=true,
  linkcolor=Maroon,
  filecolor=Maroon,
  citecolor=Blue,
  urlcolor=Blue,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{DASC 1104 Project Proposal}
\author{Braden Fowler}
\date{2020-12-03}

\begin{document}
\maketitle

My blog is available at \url{https://dasc1104-blog-project.netlify.app/}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(here)}
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{library}\NormalTok{(readxl)}
\NormalTok{knitr}\OperatorTok{::}\NormalTok{opts_chunk}\OperatorTok{$}\KeywordTok{set}\NormalTok{(}\DataTypeTok{echo =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{tidy =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Observations: 188
## Variables: 6
## $ season      <int> 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,...
## $ episode     <int> 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 1...
## $ title       <fct> Pilot, Diversity Day, Health Care, The Alliance, Basketball, H...
## $ imdb_rating <dbl> 7.6, 8.3, 7.9, 8.1, 8.4, 7.8, 8.7, 8.2, 8.4, 8.4, 8.2, 8.2, 8....
## $ total_votes <int> 3706, 3566, 2983, 2886, 3179, 2852, 3213, 2736, 2742, 2713, 25...
## $ air_date    <fct> 2005-03-24, 2005-03-29, 2005-04-05, 2005-04-12, 2005-04-19, 20...
\end{verbatim}

For this project, I am going to be looking at Office Ratings data set
contained in the office\_ratings.csv file on Tidy Tuesday's website.
This data set contains ratings of each episode from the famous US
adapted sitcom television series. The data has 188 observation and 6
variables. The variable season tells us which season of the show is
being selected from. The variable episode tells us which episode of the
season is being selected. The variable title tells us the title of the
episode being selected. The variable imdb\_rating tell us the rating
given for the episode by imdb. The variable total\_votes tells us how
many people contributed to the imdb\_rating; and finally, the variable
air\_data tells us when that specific episode was aired.

Question 1: What is the highest rated episode? Question 2: Have the
ratings of the episodes changed over time? Question 3: Which season
contains the highest average rating?

\begin{verbatim}
## Observations: 2,492
## Variables: 9
## $ date                                  <fct> 1971-04-02, 1971-04-09, 1971-04-16, ...
## $ fixed_rate_30_yr                      <dbl> 7.33, 7.31, 7.31, 7.31, 7.29, 7.38, ...
## $ fees_and_pts_30_yr                    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, 1.0,...
## $ fixed_rate_15_yr                      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
## $ fees_and_pts_15_yr                    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
## $ adjustable_rate_5_1_hybrid            <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
## $ fees_and_pts_5_1_hybrid               <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
## $ adjustable_margin_5_1_hybrid          <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
## $ spread_30_yr_fixed_and_5_1_adjustable <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, ...
\end{verbatim}

\begin{verbatim}
## Observations: 14
## Variables: 7
## $ name                                 <fct> Great Depression, Recession of 1937–1...
## $ period_range                         <fct> Aug 1929-Mar 1933ct 1929-Dec 1941, 19...
## $ duration_months                      <fct> 433 years7 months, 131 year1 month, 0...
## $ time_since_previous_recession_months <fct> 0211 year9 months, 0504 years2 months...
## $ peak_unemploy_ment                   <fct> 24.921.3%(1932)[45]–  24.9%(1933)[46]...
## $ gdp_decline_peak_to_trough           <fct> 26.7−26.7%, 03.4−18.2%, 12.7−12.7%, 0...
## $ characteristics                      <fct> "A banking panic and a collapse in th...
\end{verbatim}

\begin{verbatim}
## Observations: 26,877
## Variables: 5
## $ year        <int> 1975, 1975, 1975, 1975, 1975, 1975, 1975, 1975, 1975, 1975, 19...
## $ month       <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8,...
## $ state       <fct> AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, AK, AK...
## $ price_index <dbl> 34.63120, 35.10387, 35.49146, 35.87223, 36.28356, 36.70189, 37...
## $ us_avg      <dbl> 23.46149, 23.61079, 23.82459, 24.08920, 24.23425, 24.21718, 24...
\end{verbatim}

Using the data from TidyTuesday's website, I am going to look at
mortgage rates, times in which there was a recession in the United
States, and the housing price index over time. The first data set
contains 2,492 observations and 9 variables. The second data set
contains 14 observations and 7 variables. The third data set contains
26,877 observations and 5 variables.

Question 1: Question 2: Question 3:

\end{document}
